// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzANmiNq5yboWj9NbKAwSr90cr0abeqQs',
    appId: '1:494139613008:web:9ba06d2e802c128b3fd655',
    messagingSenderId: '494139613008',
    projectId: 'bodycontest',
    authDomain: 'bodycontest.firebaseapp.com',
    storageBucket: 'bodycontest.firebasestorage.app',
    measurementId: 'G-JWX3LKQG8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBddh7-8upjzUj3FWhTPRKiLi15nJUZLjc',
    appId: '1:494139613008:android:44ba25ab552f6cda3fd655',
    messagingSenderId: '494139613008',
    projectId: 'bodycontest',
    storageBucket: 'bodycontest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ET0uwUK_ColIOxP6ptkUa-gXz89IqKk',
    appId: '1:494139613008:ios:baba4432970402313fd655',
    messagingSenderId: '494139613008',
    projectId: 'bodycontest',
    storageBucket: 'bodycontest.firebasestorage.app',
    iosBundleId: 'com.example.bodycontest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ET0uwUK_ColIOxP6ptkUa-gXz89IqKk',
    appId: '1:494139613008:ios:baba4432970402313fd655',
    messagingSenderId: '494139613008',
    projectId: 'bodycontest',
    storageBucket: 'bodycontest.firebasestorage.app',
    iosBundleId: 'com.example.bodycontest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzANmiNq5yboWj9NbKAwSr90cr0abeqQs',
    appId: '1:494139613008:web:ee4edc5ea370f1da3fd655',
    messagingSenderId: '494139613008',
    projectId: 'bodycontest',
    authDomain: 'bodycontest.firebaseapp.com',
    storageBucket: 'bodycontest.firebasestorage.app',
    measurementId: 'G-RNNE9SFDE2',
  );
}
